/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseInput: typeof import('./../../src/components/BaseInput.vue')['default']
    Boton: typeof import('./../../src/components/Boton.vue')['default']
    Checkbox: typeof import('./../../src/components/checkbox.vue')['default']
    Pin: typeof import('./../../src/components/Pin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TransitionView: typeof import('./../../src/components/TransitionView.vue')['default']
  }
}
