/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {'(feat(buscador)': Comienzo buscador del mapa)
    BaseInput: typeof import('./../../src/components/BaseInput.vue')['default']
    Boton: typeof import('./../../src/components/Boton.vue')['default']
    Checkbox: typeof import('./../../src/components/checkbox.vue')['default']
    IwwaSearch: typeof import('~icons/iwwa/search')['default']
    LMap: typeof import('./../../src/components/LMap.vue')['default']
    Ondas: typeof import('./../../src/components/Ondas.vue')['default']
    Pin: typeof import('./../../src/components/Pin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./../../src/components/Slider.vue')['default']
    Suscripcion: typeof import('./../../src/components/Suscripcion.vue')['default']
    Title: typeof import('./../../src/components/Title.vue')['default']
    TransitionView: typeof import('./../../src/components/TransitionView.vue')['default']
  }
}
