/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseInput: typeof import('./../../src/components/Forms/BaseInput.vue')['default']
    Boton: typeof import('./../../src/components/Forms/Boton.vue')['default']
    Checkbox: typeof import('./../../src/components/Forms/checkbox.vue')['default']
    ClientProfileView: typeof import('./../../src/components/Layout/Views/ClientProfileView.vue')['default']
    ClientView: typeof import('./../../src/components/Layout/Views/ClientView.vue')['default']
    Dropdown: typeof import('./../../src/components/Forms/Dropdown.vue')['default']
    IIwwaSearch: typeof import('~icons/iwwa/search')['default']
    IMdiImageBrokenVariant: typeof import('~icons/mdi/image-broken-variant')['default']
    LMap: typeof import('./../../src/components/Layout/LMap.vue')['default']
    MapView: typeof import('./../../src/components/Layout/Views/MapView.vue')['default']
    Ondas: typeof import('./../../src/components/Layout/Ondas.vue')['default']
    Pin: typeof import('./../../src/components/Layout/Pin.vue')['default']
    RDropdownMenuCheckboxItem: typeof import('radix-vue')['DropdownMenuCheckboxItem']
    RDropdownMenuContent: typeof import('radix-vue')['DropdownMenuContent']
    RDropdownMenuItem: typeof import('radix-vue')['DropdownMenuItem']
    RDropdownMenuLabel: typeof import('radix-vue')['DropdownMenuLabel']
    RDropdownMenuRoot: typeof import('radix-vue')['DropdownMenuRoot']
    RDropdownMenuSeparator: typeof import('radix-vue')['DropdownMenuSeparator']
    RDropdownMenuTrigger: typeof import('radix-vue')['DropdownMenuTrigger']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectCategory: typeof import('./../../src/components/Forms/SelectCategory.vue')['default']
    Slider: typeof import('./../../src/components/Forms/Slider.vue')['default']
    Suscripcion: typeof import('./../../src/components/Layout/Suscripcion.vue')['default']
    Title: typeof import('./../../src/components/Layout/Title.vue')['default']
    TransitionView: typeof import('./../../src/components/Layout/Views/TransitionView.vue')['default']
    UserProfileView: typeof import('./../../src/components/Layout/Views/UserProfileView.vue')['default']
  }
}
