/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/checboxPrueba': RouteRecordInfo<'/checboxPrueba', '/checboxPrueba', Record<never, never>, Record<never, never>>,
    '/client/': RouteRecordInfo<'/client/', '/client', Record<never, never>, Record<never, never>>,
    '/client/createEvent': RouteRecordInfo<'/client/createEvent', '/client/createEvent', Record<never, never>, Record<never, never>>,
    '/client/editEvent': RouteRecordInfo<'/client/editEvent', '/client/editEvent', Record<never, never>, Record<never, never>>,
    '/client/events': RouteRecordInfo<'/client/events', '/client/events', Record<never, never>, Record<never, never>>,
    '/client/events/[id]': RouteRecordInfo<'/client/events/[id]', '/client/events/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/client/profile': RouteRecordInfo<'/client/profile', '/client/profile', Record<never, never>, Record<never, never>>,
    '/client/subscription': RouteRecordInfo<'/client/subscription', '/client/subscription', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/login/register': RouteRecordInfo<'/login/register', '/login/register', Record<never, never>, Record<never, never>>,
    '/login/registerClient': RouteRecordInfo<'/login/registerClient', '/login/registerClient', Record<never, never>, Record<never, never>>,
    '/map': RouteRecordInfo<'/map', '/map', Record<never, never>, Record<never, never>>,
    '/user/profile': RouteRecordInfo<'/user/profile', '/user/profile', Record<never, never>, Record<never, never>>,
  }
}
