/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/client/events/[id]/': RouteRecordInfo<'/client/events/[id]/', '/client/events/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/client/events/[id]/edit': RouteRecordInfo<'/client/events/[id]/edit', '/client/events/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/client/events/create': RouteRecordInfo<'/client/events/create', '/client/events/create', Record<never, never>, Record<never, never>>,
    '/client/subscription': RouteRecordInfo<'/client/subscription', '/client/subscription', Record<never, never>, Record<never, never>>,
    '/details/[id]': RouteRecordInfo<'/details/[id]', '/details/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/event/': RouteRecordInfo<'/event/', '/event', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/register/': RouteRecordInfo<'/register/', '/register', Record<never, never>, Record<never, never>>,
    '/register/client': RouteRecordInfo<'/register/client', '/register/client', Record<never, never>, Record<never, never>>,
    '/user/events/[id]/': RouteRecordInfo<'/user/events/[id]/', '/user/events/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
